# adapta.sh
latex --src -interaction=nonstopmode [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS
bibtex [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS
makeindex [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS.nlo -s nomencl.ist -o [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS.nls
latex --src -interaction=nonstopmode [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS
# latex --src -interaction=nonstopmode [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS
# pdflatex -synctex=1 -interaction=nonstopmode [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS.tex
pdflatex -synctex=1 [HESS-COELHO,\ ORSINO,\ COUTINHO]\ ADAPTATIVE\ BALANCING\ TECHNIQUES\ APPLIED\ TO\ PARALLEL\ MECHANISMS.tex
# rm -f *.aux *.log 
rm -f *.blg *.dvi *.ps *.lot *.lof *.idx *.nlo *.nls *.ilg *.out *.toc *.bbl
